### PR TITLE
fix dali resource for jakarta

### PR DESCRIPTION
**Pull request by WAvdBeek**
- resource verified with vscode

### CODE REVIEW

**Comment by marktrayer** [comment]
Can't we just revert the "bad" commit?  That's easier than pushing a new change.

**Comment by marktrayer** [comment]
Did you intend for baseline to be the default interface?

**Comment by WAvdBeek** [comment]
frankly I do not remember... just looking at the code to pass everything it was using oic.if.w as default (first listed)
but that was already in github and deemed to be wrong..

**Comment by WAvdBeek** [comment]
from the spec:
– A RETRIEVE request using the "oic.if.w" OCF Interface shall be rejected with an error response code.

Use of a RETRIEVE using the baseline OCF Interface on a Resource that exposes "oic.if.w" shall only return the Common Properties see Clause 7.3.2. A minimal implementation of a RETRIEVE response using the baseline OCF Interface on a Resource that supports "oic.if.w" shall only contain the Properties "if" and "rt".

hence the baseline interface should be used as default interface, so that a RETRIEVE works
hence this change is ok.

the code of the resource:
static void
get_dali(oc_request_t *request, oc_interface_mask_t interfaces, void *user_data)
{
  (void)user_data;  /* variable not used */
  /* TODO: SENSOR add here the code to talk to the HW if one implements a sensor.
     the call to the HW needs to fill in the global variable before it returns to this function here.
     alternative is to have a callback from the hardware that sets the global variables.
  
     The implementation always return everything that belongs to the resource.
     this implementation is not optimal, but is functionally correct and will pass CTT1.2.2 */
  bool error_state = false;
  
  
  PRINT("-- Begin get_dali: interface %d\n", interfaces);
  oc_rep_start_root_object();
  switch (interfaces) {
  case OC_IF_BASELINE:
    PRINT("   Adding Baseline info\n" );
    oc_process_baseline_interface(request->resource);
    break;
  case OC_IF_W:
    error_state = true;
    break;
  
  default:
    break;
  }
  oc_rep_end_root_object();
  if (error_state == false) {
    oc_send_response(request, OC_STATUS_OK);
  }
  else {
    oc_send_response(request, OC_STATUS_BAD_OPTION);
  }
  PRINT("-- End get_dali %s\n", btoa(error_state));
}

**Review by marktrayer — APPROVED** [review]

**Pull request merged**
